import = [
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

# import = [
#     "~/.config/alacritty/catppuccin-mocha.toml"
# ]

[env]
TERM = "xterm-256color"

[font]
normal.family = "Hack Nerd Font Mono"
size = 12

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.93
